### ISSUE TITLE
List of 100 Classes for ImageNet100

### ISSUE THREAD

**Issue by chaitanyaanimesh** [Sherrylone/Align_Representation_with_Base#1]
Hi @Sherrylone ,

Congrats for this work.

Will it be possible for you to release the list of 100 classes that you used for ImageNet100 (file referred in the code is /mnt/lustre/zhangshaofeng/workspace/whitening_224/imagenet100.txt) so that it will be easier for us to reproduce the results on this dataset and for comparisons. Thank you in advance!

**Comment by Sherrylone** [comment]
Hi, thanks for your attention to our work. You can find the list of 100 classes here https://github.com/HobbitLong/CMC/blob/master/imagenet100.txt
